import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({})

async function main() {
  console.log('🌱 Seeding database...')

  const usersData = [
    { username: 'admin', email: 'admin@wsm.com', role: 'ADMIN', balance: 10000 },
    { username: 'juan_futbol', email: 'juan@example.com', balance: 1000 },
    { username: 'maria_sports', email: 'maria@example.com', balance: 1000 },
    { username: 'pedro_trader', email: 'pedro@example.com', balance: 1000 },
    { username: 'carlos_bet', email: 'carlos@example.com', balance: 1000 },
    { username: 'Juan_rikero', email: 'juan@win.investments', balance: 1000 },
    { username: 'nacho_poker', email: 'ignacio@win.investments', balance: 1000 },
    { username: 'Gonzalo_win', email: 'gonzalo@win.investments', balance: 1000 },
    { username: 'Tecnico', email: 'esteban@win.investments', balance: 1000 },
  ]

  const users = []
  for (const u of usersData) {
    const user = await prisma.user.upsert({
      where: { username: u.username },
      update: {},
      create: u,
    })
    users.push(user)
  }

  console.log('✅ Created/Updated users:', users.map((u) => u.username))

  const marketsData = [
    {
      playerName: 'Alexis Mac Allister',
      question: '¿Mac Allister será transferido antes del cierre del mercado?',
      description: 'Mediocampista del Liverpool con interés de Barcelona y Real Madrid',
      status: 'ACTIVE',
      resolutionDate: new Date('2026-08-31'),
    },
    {
      playerName: 'Emiliano Martínez',
      question: '¿Dibu Martínez cambiará de club esta temporada?',
      description: 'Arquero del Aston Villa con interés del Bayern Munich',
      status: 'ACTIVE',
      resolutionDate: new Date('2026-08-31'),
    },
    {
      playerName: 'Enzo Fernández',
      question: '¿Enzo Fernández dejará el Chelsea en verano?',
      description: 'Mediocampista del Chelsea podría volver a Argentina',
      status: 'DRAFT',
      resolutionDate: new Date('2026-08-31'),
    },
  ]

  const markets = []
  for (const m of marketsData) {
    // We cannot easily upsert markets without a unique identifier other than ID,
    // which is autogenerated. Since this is a dev seed, we can check by playerName or simple create if logic permits.
    // However, simplest is to delete markets first or just create if not exists (query first).
    // Let's create only if not found by question (which acts somewhat like a key here).
    
    const existing = await prisma.market.findFirst({
        where: { question: m.question }
    })

    if (!existing) {
        const market = await prisma.market.create({ data: m })
        markets.push(market)
    } else {
        markets.push(existing)
    }
  }

  console.log('✅ Created markets:', markets.map((m) => m.playerName))
  console.log('🎉 Seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
